version: '3.8'

services:
    app:
        build:
            context: .
        container_name: laravel_app
        volumes:
            - .:/var/www
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel_web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
