services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: poem_app
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            APP_DEBUG: true
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/html/database/database.sqlite
            APP_URL: http://localhost:8000
